name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move generated SVGs to temp
        run: |
          mkdir -p /tmp/breakout-images
          mv output/light.svg /tmp/breakout-images/breakout-light.svg
          mv output/dark.svg /tmp/breakout-images/breakout-dark.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and force-push SVGs to target branch
        run: |
          git checkout --orphan github-breakout
          git rm -rf .
          mkdir images
          mv /tmp/breakout-images/* images/
          git add images
          git commit -m "chore: update GitHub breakout SVGs" || echo "No changes to commit"
          git push --force origin github-breakout
# name: Generate Snake Animation

# on:
#   schedule:
#     - cron: "0 0 * * *"  # executa diariamente.
#   workflow_dispatch:     # permite rodar manualmente.

# jobs:
#   generate:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Generate snake.svg
#         uses: Platane/snk@v3
#         with:
#           github_user_name: JoaoManierii
#           outputs: |
#             dist/github-snake.svg
#             dist/github-snake-dark.svg?palette=github-dark

#       - name: Push to GitHub
#         uses: EndBug/add-and-commit@v9
#         with:
#           author_name: github-actions
#           author_email: github-actions@github.com
#           message: "Generate snake.svg"
#           add: "dist/*.svg"
